# Imports

In [182]:
import pickle
import pandas as pd
from pathlib import Path
import requests
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders

In [183]:
import importlib, moduleMeteo
importlib.reload(moduleMeteo)
from moduleMeteo import (
    geocode_postal_code,
    fetch_noon_temperature,
    fetch_noon_precipitation,
    fetch_noon_wind_speed,
    load_user_csv,
    _check_conditions,
    _check_conditions_single_day,
    _check_conditions_window,
    evaluate_conditions_window,
    send_sms,
    send_twilio_test,
    send_vonage_test,
    send_vonage_sdk,
    decision_maker_daily,
    envoyer_email
    
)

# Chargement des données du user

In [184]:
# Sélection du CSV (drag & drop)
from IPython.display import display
from pathlib import Path

# Essayez d'abord un chemin par défaut; sinon, proposer un uploader
csv_path = None
try_default = Path("./nouvelle_bdd.csv")
if try_default.exists():
    csv_path = try_default
else:
    try:
        from ipywidgets import FileUpload, Button, VBox, HTML
        uploader = FileUpload(accept='.csv', multiple=False)
        status = HTML("<b>Glissez-déposez votre CSV puis cliquez sur 'Utiliser ce fichier'</b>")
        use_btn = Button(description="Utiliser ce fichier", button_style='success')
        selected_path = Path("./uploaded_user_bdd.csv")

        def _on_click(_):
            if not uploader.value:
                status.value = "<span style='color:red'>Aucun fichier sélectionné.</span>"
                return
            val = uploader.value
            content = None
            # ipywidgets<8: dict-like; ipywidgets>=8: tuple of UploadedFile
            if isinstance(val, dict):
                key = next(iter(val))
                meta = val[key]
                content = meta.get('content') or meta.get('data')
            else:
                item = next(iter(val)) if len(val) else None
                if item is None:
                    status.value = "<span style='color:red'>Aucun fichier sélectionné.</span>"
                    return
                content = getattr(item, 'content', None) or getattr(item, 'data', None)
            if content is None:
                status.value = "<span style='color:red'>Impossible de lire le contenu du fichier.</span>"
                return
            with open(selected_path, 'wb') as f:
                f.write(content)
            globals()['csv_path'] = selected_path
            status.value = f"Fichier sauvegardé: {selected_path.resolve()}"

        use_btn.on_click(_on_click)
        display(VBox([status, uploader, use_btn]))
    except Exception as e:
        raise FileNotFoundError("CSV introuvable et widgets non disponibles. Spécifiez un chemin valide dans csv_path.")

In [185]:
# Charger uniquement depuis CSV (pickle supprimé)
from pathlib import Path as _P
from datetime import datetime

csv_path = _P(csv_path) if not isinstance(csv_path, _P) else csv_path
if not csv_path.exists():
    raise FileNotFoundError(f"CSV introuvable: {csv_path.resolve()}")

df_magasins = load_user_csv(str(csv_path))

print(f"✅ CSV chargé: {len(df_magasins)} magasin(s)")
print(f"\nColonnes disponibles: {list(df_magasins.columns)}")
print(f"\nAperçu des données:")
df_magasins.head()

✅ CSV chargé: 2 magasin(s)

Colonnes disponibles: ['magasin', 'code_postal', 'conditions_meteo', 'delai_jours_avant', 'delai_jours_apres', 'derniere_campagne', 'mail', 'temp_min', 'precipitations_max', 'vitesse_vent_max', 'temp_max', 'precipitations_min', 'vitesse_vent_min']

Aperçu des données:

,magasin,code_postal,conditions_meteo,delai_jours_avant,delai_jours_apres,derniere_campagne,mail,temp_min,precipitations_max,vitesse_vent_max,temp_max,precipitations_min,vitesse_vent_min
0,Magasin-59000,59000,"{'temp_min': 4, 'precipita...",2,3,NaT,khairkhair012@gmail.com,4,1.5,30,NaN,NaN,NaN
1,Magasin-59100,59100,"{'temp_min': 12, 'precipit...",1,2,NaT,user2@example.com,12,1.0,20,NaN,NaN,NaN

In [186]:
# Afficher les paramètres de fenêtre pour chaque magasin
print("=== PARAMÈTRES DE FENÊTRE PAR MAGASIN ===")
for idx, row in df_magasins.iterrows():
    magasin = row.get("magasin", "N/A")
    cp = row.get("code_postal", "N/A")
    avant = row.get("delai_jours_avant", 0)
    apres = row.get("delai_jours_apres", 0)
    print(f"{magasin} (CP: {cp}): {avant} jours avant, {apres} jours après")

=== PARAMÈTRES DE FENÊTRE PAR MAGASIN ===
Magasin-59000 (CP: 59000): 2 jours avant, 3 jours après
Magasin-59100 (CP: 59100): 1 jours avant, 2 jours après

# Verification des conditions sous tout le time-stamp

In [187]:
# Évaluation des conditions avec affichage JOUR PAR JOUR amélioré
target_date = None
print("=== ÉVALUATION DES CONDITIONS MÉTÉO (JOUR PAR JOUR) ===")
date_affichage = target_date if target_date else "Aujourd'hui"
print(f"Date cible: {date_affichage}")

from moduleMeteo import decision_maker_daily

decisions, df_daily = decision_maker_daily(df_magasins, target_date=target_date)

print(f"\n✅ {len(decisions)} magasin(s) déclenchent une alerte:")
for magasin, mail in decisions.items():
    print(f"  - {magasin} → {mail if mail else 'Pas de mail'}")

# ✅ AMÉLIORATION : Restructurer le DataFrame pour plus de clarté
print("\n" + "="*140)
print("📊 RÉSULTATS DÉTAILLÉS JOUR PAR JOUR")
print("="*140 + "\n")

# Configurer pandas
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 140)
pd.set_option('display.precision', 2)

# Afficher par magasin avec conditions
for magasin in df_daily['magasin'].unique():
    df_magasin = df_daily[df_daily['magasin'] == magasin].copy()
    
    # Extraire les informations du magasin
    mail = df_magasin['mail'].iloc[0] if 'mail' in df_magasin.columns else "N/A"
    cp = df_magasin['code_postal'].iloc[0] if 'code_postal' in df_magasin.columns else "N/A"
    conditions = df_magasin['conditions'].iloc[0] if 'conditions' in df_magasin.columns else {}
    
# ✅ Afficher l'en-tête du magasin avec CONDITIONS
    print(f"\n🏪 {magasin} | 📧 {mail} | 📍 CP: {cp}")
    print(f"📋 CONDITIONS REQUISES:")
    if isinstance(conditions, dict):
        cond_parts = []
        
        # Température
        if 'temp_min' in conditions and 'temp_max' in conditions:
            cond_parts.append(f"🌡️  {conditions['temp_min']}°C < Temp < {conditions['temp_max']}°C")
        elif 'temp_min' in conditions:
            cond_parts.append(f"🌡️  Temp > {conditions['temp_min']}°C")
        elif 'temp_max' in conditions:
            cond_parts.append(f"🌡️  Temp < {conditions['temp_max']}°C")
        
        # Précipitations
        if 'precipitations_min' in conditions and 'precipitations_max' in conditions:
            cond_parts.append(f"💧 {conditions['precipitations_min']} mm < Précip < {conditions['precipitations_max']} mm")
        elif 'precipitations_min' in conditions:
            cond_parts.append(f"💧 Précip > {conditions['precipitations_min']} mm")
        elif 'precipitations_max' in conditions:
            cond_parts.append(f"💧 Précip < {conditions['precipitations_max']} mm")
        
        # Vitesse du vent
        if 'vitesse_vent_min' in conditions and 'vitesse_vent_max' in conditions:
            cond_parts.append(f"💨 {conditions['vitesse_vent_min']} km/h < Vent < {conditions['vitesse_vent_max']} km/h")
        elif 'vitesse_vent_min' in conditions:
            cond_parts.append(f"💨 Vent > {conditions['vitesse_vent_min']} km/h")
        elif 'vitesse_vent_max' in conditions:
            cond_parts.append(f"💨 Vent < {conditions['vitesse_vent_max']} km/h")
        
        
        # Afficher les conditions
        if cond_parts:
            for part in cond_parts:
                print(f"   {part}")
        else:
            print("   Aucune condition définie")

        print("-" * 140)
    
    # ✅ GARDER TOUS LES JOURS (y compris J-2, J-1 avec NaN)
    df_display = df_magasin[['date', 'jour_relatif', 'temp_12h', 'vent_12h', 
                             'precipitations_12h', 'state']].copy()
    
    # Renommer pour plus de clarté
    df_display.columns = ['Date', 'Jour', 'Temp (°C)', 'Vent (km/h)', 
                          'Précip (mm)', 'Conforme']
    
    # ✅ Remplacer NaN par un symbole plus visible
    df_display = df_display.fillna({
        'Temp (°C)': '—',
        'Vent (km/h)': '—',
        'Précip (mm)': '—',
        'UV': '—'
    })
    
    # Afficher le tableau complet
    display(df_display)
    
    # ✅ Statistiques SEULEMENT sur les jours avec données
    df_with_data = df_magasin[df_magasin['temp_12h'].notna()]
    nb_jours_total = len(df_magasin)
    nb_jours_avec_data = len(df_with_data)
    nb_conformes = df_with_data['state'].sum() if not df_with_data.empty else 0
    taux = (nb_conformes/nb_jours_avec_data*100) if nb_jours_avec_data > 0 else 0
    
    print(f"\n📊 Statistiques:")
    print(f"   • Total jours analysés: {nb_jours_total} (dont {nb_jours_total - nb_jours_avec_data} jours passés sans données)")
    print(f"   • Jours avec prévisions: {nb_jours_avec_data}")
    print(f"   • Jours conformes: {nb_conformes}/{nb_jours_avec_data} ({taux:.1f}%)")
    
    # ✅ Identifier les jours problématiques (seulement ceux avec données)
    if nb_jours_avec_data > 0 and nb_conformes < nb_jours_avec_data:
        jours_pb = df_with_data[~df_with_data['state']]['jour_relatif'].tolist()
        print(f"   ⚠️  Jours NON conformes: {', '.join(jours_pb)}")
    
    # ✅ Note sur les jours passés
    jours_passes = df_magasin[df_magasin['temp_12h'].isna()]['jour_relatif'].tolist()
    if jours_passes:
        print(f"   ℹ️  Jours passés (données historiques non disponibles): {', '.join(jours_passes)}")
    
    print()

=== ÉVALUATION DES CONDITIONS MÉTÉO (JOUR PAR JOUR) ===
Date cible: Aujourd'hui
📅 Récupération données historiques: 2025-11-06 à 2025-11-07 (J-2 à J-1)
✅ Données historiques fusionnées: 2 jours passés
📅 Récupération données historiques: 2025-11-07 à 2025-11-07 (J-1 à J-1)
✅ Données historiques fusionnées: 1 jours passés

✅ 1 magasin(s) déclenchent une alerte:
  - Magasin-59000 → khairkhair012@gmail.com

============================================================================================================================================
📊 RÉSULTATS DÉTAILLÉS JOUR PAR JOUR
============================================================================================================================================


🏪 Magasin-59000 | 📧 khairkhair012@gmail.com | 📍 CP: 59000
📋 CONDITIONS REQUISES:
   🌡️  Temp > 4°C
   💧 Précip < 1.5 mm
   💨 Vent < 30 km/h
--------------------------------------------------------------------------------------------------------------------------------------------

         Date Jour  Temp (°C)  Vent (km/h)  Précip (mm)  Conforme
0  2025-11-06  J-2       14.2          5.2          0.0      True
1  2025-11-07  J-1       12.8         13.1          0.0      True
2  2025-11-08    J       10.6          7.9          0.1      True
3  2025-11-09  J+1       13.0          9.4          0.0      True
4  2025-11-10  J+2       10.3         18.7          0.0      True
5  2025-11-11  J+3       10.6         22.9          0.0      True

📊 Statistiques:
   • Total jours analysés: 6 (dont 0 jours passés sans données)
   • Jours avec prévisions: 6
   • Jours conformes: 6/6 (100.0%)


🏪 Magasin-59100 | 📧 user2@example.com | 📍 CP: 59100
📋 CONDITIONS REQUISES:
   🌡️  Temp > 12°C
   💧 Précip < 1.0 mm
   💨 Vent < 20 km/h
--------------------------------------------------------------------------------------------------------------------------------------------

         Date Jour  Temp (°C)  Vent (km/h)  Précip (mm)  Conforme
6  2025-11-07  J-1       12.8         12.8          0.0      True
7  2025-11-08    J       10.8          9.0          0.0     False
8  2025-11-09  J+1       12.9          9.7          0.0      True
9  2025-11-10  J+2       10.1         19.1          0.0     False

📊 Statistiques:
   • Total jours analysés: 4 (dont 0 jours passés sans données)
   • Jours avec prévisions: 4
   • Jours conformes: 2/4 (50.0%)
   ⚠️  Jours NON conformes: J, J+2

# Qui notifier?

In [188]:
# ============================================================================
# 📧 LISTE DES MAGASINS À ALERTER
# ============================================================================

print("\n" + "="*140)
print("📧 MAGASINS À ALERTER (100% CONDITIONS RESPECTÉES)")
print("="*140)

# ✅ Liste simple des magasins
magasins_a_alerter = list(decisions.keys())

print(f"\n✅ Nombre de magasins à alerter: {len(magasins_a_alerter)}")
print(f"\n📋 LISTE DES MAGASINS:")
print(magasins_a_alerter)

# ✅ Détails avec emails
if magasins_a_alerter:
    print(f"\n📨 DÉTAILS DES ALERTES:")
    for i, (magasin, mail) in enumerate(decisions.items(), 1):
        email_display = mail if mail else "⚠️  Pas d'email configuré"
        print(f"   {i}. {magasin}")
        print(f"      └─ Email: {email_display}")
    
    # ✅ Liste des emails uniquement
    emails_valides = [mail for mail in decisions.values() if mail]
    print(f"\n📬 EMAILS À NOTIFIER ({len(emails_valides)}):")
    print(emails_valides)
else:
    print("\n❌ Aucun magasin à alerter")

print("="*140)

============================================================================================================================================
📧 MAGASINS À ALERTER (100% CONDITIONS RESPECTÉES)
============================================================================================================================================

✅ Nombre de magasins à alerter: 1

📋 LISTE DES MAGASINS:
['Magasin-59000']

📨 DÉTAILS DES ALERTES:
   1. Magasin-59000
      └─ Email: khairkhair012@gmail.com

📬 EMAILS À NOTIFIER (1):
['khairkhair012@gmail.com']
============================================================================================================================================

# Envoyer les mails

In [189]:
print(decisions)

{'Magasin-59000': 'khairkhair012@gmail.com'}

In [190]:
EXPEDITEUR = "kamm.94.ai@gmail.com"
MOT_DE_PASSE = "fmvd aclj quap mxax"

In [ ]:
for magasin, email in decisions.items():
    # Récupération du dictionnaire de conditions météo pour ce magasin
    conditions = df_magasins.loc[df_magasins["magasin"] == magasin, "conditions_meteo"].iloc[0]

    # Traductions lisibles pour le mail
    noms_conditions = {
        "temp_min": "Température minimale",
        "temp_max": "Température maximale",
        "precipitations_min": "Précipitations minimales",
        "precipitations_max": "Précipitations maximales",
        "vitesse_vent_min": "Vitesse minimale du vent",
        "vitesse_vent_max": "Vitesse maximale du vent",
    }

    # Construction dynamique du message
    details = ""
    for cle, label in noms_conditions.items():
        valeur = conditions.get(cle)
        if valeur not in [None, "", "nan"]:  # ne pas afficher les champs vides
            # Ajout d'unité adaptée
            if "temp" in cle:
                unite = "°C"
            elif "precipitations" in cle:
                unite = "mm"
            elif "vent" in cle:
                unite = "km/h"
            else:
                unite = ""
            details += f" - {label} : {valeur} {unite}\n"

    # Corps du message complet
    corps_message = (
        f"Bonjour,\n\n"
        f"Nous vous informons que les conditions météorologiques que vous avez sélectionnées sont satisfaites :\n"
        f"{details}\n"
        f"Cordialement,\n"
        f"L’équipe Wellpack"
    )

    # Envoi de l'email
    envoyer_email(
        expediteur_email=EXPEDITEUR,
        expediteur_password=MOT_DE_PASSE,
        destinataire_email=email,
        sujet="Alerte liée aux conditions météorologiques",
        corps_message=corps_message,
    )

✓ Email envoyé avec succès à khairkhair012@gmail.com